### ISSUE TITLE
Fix KeyError: 'hooks'

### ISSUE THREAD

**Issue by jcfr** [Slicer/github-circleci-trigger#1]
```
2017-10-18T23:01:07.829717+00:00 app[web.1]: Traceback (most recent call last):
2017-10-18T23:01:07.829721+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
2017-10-18T23:01:07.829722+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-10-18T23:01:07.829722+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
2017-10-18T23:01:07.829723+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-10-18T23:01:07.829724+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
2017-10-18T23:01:07.829724+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-10-18T23:01:07.829725+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
2017-10-18T23:01:07.829726+00:00 app[web.1]:     rv = self.dispatch_request()
2017-10-18T23:01:07.829726+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
2017-10-18T23:01:07.829727+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-10-18T23:01:07.829728+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/github_webhook/webhook.py", line 73, in _postreceive
2017-10-18T23:01:07.829729+00:00 app[web.1]:     hook(data)
2017-10-18T23:01:07.829729+00:00 app[web.1]:   File "/app/github-circleci-trigger.py", line 47, in with_ip_check
2017-10-18T23:01:07.829730+00:00 app[web.1]:     hook_blocks = requests.get('https://api.github.com/meta').json()['hooks']
2017-10-18T23:01:07.829731+00:00 app[web.1]: KeyError: 'hooks'

```

**Comment by jcfr** [comment]
Closing. This was probably an intermittent failure

```python
>>> import requests
>>> requests.get('https://api.github.com/meta').json()['hooks']
['192.30.252.0/22', '185.199.108.0/22', '140.82.112.0/20', '143.55.64.0/20', '2a0a:a440::/29', '2606:50c0::/32']
```
