### ISSUE TITLE
On tag pushed: Fix  `'NoneType' object has no attribute 'lstrip'` because of  `branch = data['base_ref'].lstrip('refs/heads/')`

### ISSUE THREAD

**Issue by jcfr** [Slicer/github-circleci-trigger#2]
```
2017-10-18T10:06:41.242755+00:00 app[web.1]: [2017-10-18 10:06:41,241] ERROR in app: Exception on /postreceive [POST]
2017-10-18T10:06:41.242776+00:00 app[web.1]: Traceback (most recent call last):
2017-10-18T10:06:41.242779+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
2017-10-18T10:06:41.242780+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-10-18T10:06:41.242782+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
2017-10-18T10:06:41.242783+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-10-18T10:06:41.242783+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
2017-10-18T10:06:41.242784+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-10-18T10:06:41.242784+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
2017-10-18T10:06:41.242785+00:00 app[web.1]:     rv = self.dispatch_request()
2017-10-18T10:06:41.242786+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
2017-10-18T10:06:41.242787+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-10-18T10:06:41.242788+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/github_webhook/webhook.py", line 73, in _postreceive
2017-10-18T10:06:41.242789+00:00 app[web.1]:     hook(data)
2017-10-18T10:06:41.242790+00:00 app[web.1]:   File "/app/github-circleci-trigger.py", line 60, in with_ip_check
2017-10-18T10:06:41.242791+00:00 app[web.1]:     return func(*args, **kwargs)
2017-10-18T10:06:41.242791+00:00 app[web.1]:   File "/app/github-circleci-trigger.py", line 134, in on_push
2017-10-18T10:06:41.242792+00:00 app[web.1]:     branch = data['base_ref'].lstrip('refs/heads/')
2017-10-18T10:06:41.242793+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'lstrip'
```

Payload:

```
{
  "ref": "refs/tags/v4.8.0",
  "before": "0000000000000000000000000000000000000000",
  "after": "8993a98935c1586e9445ac7354343ae959ebfc36",
  "created": true,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/Slicer/Slicer/compare/v4.8.0",
  "commits": [

  ],
  "head_commit": {
    "id": "944c364a6dd95f1e57dca9ee6b5e1878951de184",
    "tree_id": "d32e3925b43d2e5766b7cb7e849463d24bcd83b8",
    "distinct": true,
    "message": "ENH: Slicer 4.8.0\n\ngit-svn-id: http://svn.slicer.org/Slicer4/trunk@26489 3bd1e089-480b-0410-8dfb-8563597acbee",
    "timestamp": "2017-10-18T09:11:33Z",
    "url": "https://github.com/Slicer/Slicer/commit/944c364a6dd95f1e57dca9ee6b5e1878951de184",
    "author": {
      "name": "jcfr",
      "email": "jcfr@3bd1e089-480b-0410-8dfb-8563597acbee",
      "username": "jcfr"
    },
    "committer": {
      "name": "jcfr",
      "email": "jcfr@3bd1e089-480b-0410-8dfb-8563597acbee",
      "username": "jcfr"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "CMakeLists.txt",
      "Utilities/Scripts/SlicerWizard/__version__.py"
    ]
  },
  "repository": {
    "id": 2006302,
    "name": "Slicer",
    "full_name": "Slicer/Slicer",
    "owner": {
      [...]
    },
    "private": false,
    "html_url": "https://github.com/Slicer/Slicer",
    "description": "Multi-platform, free open source software for visualization and image computing.",
    "fork": false,
    "url": "https://github.com/Slicer/Slicer",
    "forks_url": "https://api.github.com/repos/Slicer/Slicer/forks",
    "keys_url": "https://api.github.com/repos/Slicer/Slicer/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Slicer/Slicer/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Slicer/Slicer/teams",
    "hooks_url": "https://api.github.com/repos/Slicer/Slicer/hooks",
    "issue_events_url": "https://api.github.com/repos/Slicer/Slicer/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Slicer/Slicer/events",
    "assignees_url": "https://api.github.com/repos/Slicer/Slicer/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Slicer/Slicer/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Slicer/Slicer/tags",
    "blobs_url": "https://api.github.com/repos/Slicer/Slicer/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Slicer/Slicer/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Slicer/Slicer/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Slicer/Slicer/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Slicer/Slicer/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Slicer/Slicer/languages",
    "stargazers_url": "https://api.github.com/repos/Slicer/Slicer/stargazers",
    "contributors_url": "https://api.github.com/repos/Slicer/Slicer/contributors",
    "subscribers_url": "https://api.github.com/repos/Slicer/Slicer/subscribers",
    "subscription_url": "https://api.github.com/repos/Slicer/Slicer/subscription",
    "commits_url": "https://api.github.com/repos/Slicer/Slicer/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Slicer/Slicer/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Slicer/Slicer/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Slicer/Slicer/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Slicer/Slicer/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Slicer/Slicer/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Slicer/Slicer/merges",
    "archive_url": "https://api.github.com/repos/Slicer/Slicer/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Slicer/Slicer/downloads",
    "issues_url": "https://api.github.com/repos/Slicer/Slicer/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Slicer/Slicer/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Slicer/Slicer/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Slicer/Slicer/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Slicer/Slicer/labels{/name}",
    "releases_url": "https://api.github.com/repos/Slicer/Slicer/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Slicer/Slicer/deployments",
    "created_at": 1309955238,
    "updated_at": "2017-10-09T08:32:35Z",
    "pushed_at": 1508321300,
    "git_url": "git://github.com/Slicer/Slicer.git",
    "ssh_url": "git@github.com:Slicer/Slicer.git",
    "clone_url": "https://github.com/Slicer/Slicer.git",
    "svn_url": "https://github.com/Slicer/Slicer",
    "homepage": "http://www.slicer.org",
    "size": 436855,
    [...]
    "master_branch": "master",
    "organization": "Slicer"
  },
  "pusher": {
    "name": "jcfr",
    "email": "jchris.fillionr@kitware.com"
  },
  "organization": {
    [...]
  },
  "sender": {
    [...]
  }
}
```

**Comment by jcfr** [comment]
* CircleCI worker is now properly triggered

but the following error is reported during the `Set GitHub status to 'pending'` step.

See https://circleci.com/gh/Slicer/apidocs.slicer.org/1103

```
#!/bin/bash -eo pipefail
slicer-apidocs-builder \
  --status-update-state pending \
  --status-update-repo-name Slicer/Slicer \
  --status-update-revision ${SLICER_REPO_REVISION} \
  --status-update-target-url ${CIRCLE_BUILD_URL}


Apidocs status update parameters
  * state .......................: pending
  * repo_name ...................: Slicer/Slicer
  * revision ....................: 8993a98935c1586e9445ac7354343ae959ebfc36
  * github_token ................: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  * target_url ..................: https://circleci.com/gh/Slicer/apidocs.slicer.org/1103
Traceback (most recent call last):
  File "/usr/local/bin/slicer-apidocs-builder", line 11, in <module>
    load_entry_point('slicer-apidocs-builder==0.1.0', 'console_scripts', 'slicer-apidocs-builder')()
  File "/usr/local/lib/python2.7/site-packages/slicer_apidocs_builder/__init__.py", line 527, in main
    exit(cli())
  File "/usr/local/lib/python2.7/site-packages/slicer_apidocs_builder/__init__.py", line 422, in cli
    status_update_branch_or_tag=slicer_repo_branch_or_tag
  File "/usr/local/lib/python2.7/site-packages/slicer_apidocs_builder/__init__.py", line 282, in _apidocs_status_update
    target_url=status_update_target_url
  File "/usr/local/lib/python2.7/site-packages/github3/decorators.py", line 38, in auth_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/github3/repos/repo.py", line 809, in create_status
    json = self._json(self._post(url, data=data), 201)
  File "/usr/local/lib/python2.7/site-packages/github3/models.py", line 100, in _json
    if self._boolean(response, status_code, 404) and response.content:
  File "/usr/local/lib/python2.7/site-packages/github3/models.py", line 121, in _boolean
    raise GitHubError(response)
github3.models.GitHubError: 422 No commit found for SHA: 8993a98935c1586e9445ac7354343ae959ebfc36
Exited with code 1
```

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/Slicer/github-circleci-trigger/commit/44bd69f1741fd905fd32a09ba3169dbbc187705f
