### ISSUE TITLE
module 'flask.logging' has no attribute 'PROD_LOG_FORMAT'

### ISSUE THREAD

**Issue by jcfr** [Slicer/github-circleci-trigger#4]
Following transition to Python 3.10, the following is reported:

```
2022-08-14T22:39:24.090636+00:00 heroku[web.1]: State changed from starting to up
2022-08-14T22:45:06.735106+00:00 app[web.1]: [2022-08-14 22:45:06,734] ERROR in app: Exception on /postreceive [POST]
2022-08-14T22:45:06.735114+00:00 app[web.1]: Traceback (most recent call last):
2022-08-14T22:45:06.735115+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
2022-08-14T22:45:06.735115+00:00 app[web.1]: response = self.full_dispatch_request()
2022-08-14T22:45:06.735116+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 1812, in full_dispatch_request
2022-08-14T22:45:06.735117+00:00 app[web.1]: self.ensure_sync(func)()
2022-08-14T22:45:06.735117+00:00 app[web.1]: File "/app/github-circleci-trigger.py", line 25, in setup_logging
2022-08-14T22:45:06.735117+00:00 app[web.1]: handler.setFormatter(logging.Formatter(flask_logging.PROD_LOG_FORMAT))
2022-08-14T22:45:06.735118+00:00 app[web.1]: AttributeError: module 'flask.logging' has no attribute 'PROD_LOG_FORMAT'
```

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/Slicer/github-circleci-trigger/commit/3cbfd4598502ae836851bd856baebc7aac55e6f8
